### ISSUE TITLE
Can't type : (colon)

### ISSUE THREAD

**Issue by SamCyanide** [Vogtinator/micropython#1]
There are no documents on how to use this. I figured out you can type a double quote by pressing shift+\* but I have not found a key combination to type "" or ''. You guys should make a readme.

**Comment by SamCyanide** [comment]
Sorry, this is for the TI NSPIRE. Also by readme I meant maybe more comprehensive documentation if possible.

**Comment by hazelduvall** [comment]
colon is shift+period. It took me a while to figure that out too.

**Comment by SamCyanide** [comment]
Oh wow I didn't even think about . and the - key. Guess I generalize them with the numbers. Thanks!
