### ISSUE TITLE
Can't use HIDn - drivers with Nspire MicroPython

### ISSUE THREAD

**Issue by N0ury** [Vogtinator/micropython#10]
My USB external keyboard is usable with my TI-Nspire, except with micropython app.
Nothing happens.
I'm using this [driver](https://tiplanet.org/forum/archives_voir.php?id=12928)

**Comment by Vogtinator** [comment]
Yes, nspire-io does not use the OS input events, it only reads the keypad. This would need to be changed in nspire-io, but is AFAICT not really compatible. So WONTFIX.
