### ISSUE TITLE
Micropython doesn't compile

### ISSUE THREAD

**Issue by Ti64CLi** [Vogtinator/micropython#11]
I can't manage to compile micropython, with the nspire branch.
I get those errors:
In file included from texture.c:16:
texture.c: In function ‘nsp_texture_init’:
/mnt/c/Users/neuronix/Ndless/ndless-sdk/bin/../include/libndls.h:164:95: error: expected ‘;’ before ‘}’ token
  #define SCREEN_BASE_ADDRESS ({"SCREEN_BASE_ADDRESS got removed in favor of the lcd_blit API."})
                                                                                               ^
texture.c:44:3: note: in expansion of macro ‘SCREEN_BASE_ADDRESS’
   SCREEN_BASE_ADDRESS = malloc(320*240*2);
   ^~~~~~~~~~~~~~~~~~~
texture.c:44:23: error: lvalue required as left operand of assignment
   SCREEN_BASE_ADDRESS = malloc(320*240*2);
                       ^
In file included from texture.c:16:
texture.c: In function ‘nsp_texture_deinit’:
/mnt/c/Users/neuronix/Ndless/ndless-sdk/bin/../include/libndls.h:164:95: error: expected ‘;’ before ‘}’ token
  #define SCREEN_BASE_ADDRESS ({"SCREEN_BASE_ADDRESS got removed in favor of the lcd_blit API."})
                                                                                               ^
texture.c:54:15: note: in expansion of macro ‘SCREEN_BASE_ADDRESS’
   void *buf = SCREEN_BASE_ADDRESS;
               ^~~~~~~~~~~~~~~~~~~
/mnt/c/Users/neuronix/Ndless/ndless-sdk/bin/../include/libndls.h:164:95: error: expected ‘;’ before ‘}’ token
  #define SCREEN_BASE_ADDRESS ({"SCREEN_BASE_ADDRESS got removed in favor of the lcd_blit API."})
                                                                                               ^
texture.c:55:3: note: in expansion of macro ‘SCREEN_BASE_ADDRESS’
   SCREEN_BASE_ADDRESS = (void*) 0xA4000100;
   ^~~~~~~~~~~~~~~~~~~
texture.c:55:23: error: lvalue required as left operand of assignment
   SCREEN_BASE_ADDRESS = (void*) 0xA4000100;
                       ^
In file included from texture.c:16:
texture.c: In function ‘nsp_texture_display’:
/mnt/c/Users/neuronix/Ndless/ndless-sdk/bin/../include/libndls.h:164:95: error: expected ‘;’ before ‘}’ token
  #define SCREEN_BASE_ADDRESS ({"SCREEN_BASE_ADDRESS got removed in favor of the lcd_blit API."})
                                                                                               ^
texture.c:112:21: note: in expansion of macro ‘SCREEN_BASE_ADDRESS’
   memcpy((uint16_t*)SCREEN_BASE_ADDRESS, self->bitmap, 320*240*2);
                     ^~~~~~~~~~~~~~~~~~~
/mnt/c/Users/neuronix/Ndless/ndless-sdk/bin/../include/libndls.h:164:95: error: expected ‘;’ before ‘}’ token
  #define SCREEN_BASE_ADDRESS ({"SCREEN_BASE_ADDRESS got removed in favor of the lcd_blit API."})
                                                                                               ^
texture.c:116:66: note: in expansion of macro ‘SCREEN_BASE_ADDRESS’
   uint16_t *ptr = self->bitmap + 320*240, *ptr_inv = ((uint16_t*)SCREEN_BASE_ADDRESS) + 320*240;
                                                                  ^~~~~~~~~~~~~~~~~~~
../py/mkrules.mk:46: recipe for target 'build/./texture.o' failed
make: *** [build/./texture.o] Error 1

I see what's causing this issue, but I can't figure out a way to correct it.
Thanks for helping me

**Comment by The-Compiler** [comment]
Can you try the `next-next` branch?

**Comment by Ti64CLi** [comment]
I try

Le lun. 16 sept. 2019 à 18:51, Florian Bruhin <notifications@github.com> a
écrit :

**Comment by Ti64CLi** [comment]
Thanks, it's working

**Comment by The-Compiler** [comment]
@Vogtinator Maybe `next-next` should be merged into `master`, given that it's clearly an improvement over the current `master` branch, no?

**Comment by Vogtinator** [comment]
@The-Compiler It's not entirely feature compatible and not as tested though.

The master branch should still build and work with `-D OLD_SCREEN_API` added to CFLAGS, maybe I should just commit that?

**Comment by Vogtinator** [comment]
On second thought, that would break nsp_texture on HW-W+, so might not be the best option...

I'll just set `next-next` as the default branch on github and be optimistic that sometime in the future I've got enough time to properly rebase it on micropython master (and maybe send it upstream).
