### ISSUE TITLE
Import other files on the nspire cx

### ISSUE THREAD

**Issue by okaufmann** [Vogtinator/micropython#5]
Hi,

I'm playing around with the micropython package on my nspire cx cas.
Everything works fine except the imports. I'm new to python.
How can I import functions from other files from relative paths or form otherwhere?

I tried to to the simplest was and have a `lib.py.tns` and a `run.py.tns` in the same folder. When i try to run the following in `run.py.tns` I got an `no module named "lib"` errror.

```python
# run.py.tns
import lib # error

print(lib.test())
```

Do you have some advices for me ?

Thanks

**Comment by Vogtinator** [comment]
I never tried imports, maybe it requires ".py" and not ".py.tns" as file extension? You can check for that by doing os.rename first and trying again.

**Comment by okaufmann** [comment]
to overwrite the import routine ?

**Comment by Vogtinator** [comment]
What do you mean by that?

I'm suggesting that you try

```
import os
os.rename("lib.py.tns", "lib.py")
````

**Comment by parrotgeek1** [comment]
You should edit the code to always automatically add/strip .tns from files in the documents folder. 

A

**Comment by parrotgeek1** [comment]
Also it needs to support HW-W

**Comment by Vogtinator** [comment]
> Also it needs to support HW-W

That's not micropython, it's nspire-io that needs to be fixed.

**Comment by jkcoxson** [comment]
For posterity and future reference, imported py files must be in the same folder as Ndless (not MicroPython or the running file), or you can push a path with sys.
