### ISSUE TITLE
Rendering issues on 4.5 with updated branch

### ISSUE THREAD

**Issue by The-Compiler** [Vogtinator/micropython#8]
After working on #7 I upgraded my nspire to ndless 4.5 and OS 4.5.0.1180. After the upgrade, the old Micropython release works fine, but my build looks like this:

![image](https://user-images.githubusercontent.com/625793/30231330-b0dc7404-94ea-11e7-802a-081ee91680af.png)

The `hello_cpp` I built from sources looks fine though... any idea what's going wrong there?

**Comment by Vogtinator** [comment]
You are probably using a HW-W+ calc, right?

This is likely caused by a mixture of code using the old LCD API (nspire/texture.c) and the new LCD API (nspire-io, part of the ndless sdk). The proper solution is to port nspire/texture.c to use the new LCD API.
This should be trivial for CX as it just needs to call lcd_blit (lcd_init is done by nspire-io already) in the display function. For non-CX however it needs to convert the texture to a 4 bit one to not break nspire-io drawing.

**Comment by The-Compiler** [comment]
I have a P-0416X datecode, so I think so?

> For non-CX however it needs to convert the texture to a 4 bit one to not break nspire-io drawing.

I guess I'll have to pass on that one - I have no idea how those textures look in memory exactly, and I don't have a non-CX calc to test with.

**Comment by The-Compiler** [comment]
I gave it a quick try, unfortunately without any luck:

```diff
diff --git a/nspire/Makefile b/nspire/Makefile
index ebfe41a6..03304994 100644
--- a/nspire/Makefile
+++ b/nspire/Makefile
@@ -36,7 +36,7 @@ endif
 
 # compiler settings
 CWARN = -Wall -Werror -Wno-error=cpp -Wno-error=format
-CFLAGS = $(INC) $(CWARN) -ansi -std=gnu99 $(CFLAGS_MOD) $(COPT) $(CFLAGS_EXTRA) -D OLD_SCREEN_API
+CFLAGS = $(INC) $(CWARN) -ansi -std=gnu99 $(CFLAGS_MOD) $(COPT) $(CFLAGS_EXTRA)
 
 LDFLAGS = $(LDFLAGS_MOD) -lm $(LDFLAGS_EXTRA) -Wl,--nspireio
 
diff --git a/nspire/texture.c b/nspire/texture.c
index f6dcfaf8..7835c796 100644
--- a/nspire/texture.c
+++ b/nspire/texture.c
@@ -39,22 +39,12 @@
 
 void nsp_texture_init()
 {
-       if(!has_colors)
-       {
-               SCREEN_BASE_ADDRESS = malloc(320*240*2);
-               (*(uint32_t*)0xC000001C) = ((*(uint32_t*)0xC000001C) & ~0b1110) | 0b1000; // Switch to 16-bit mode
-       }
+       // already init'ed by nspire-io
 }
 
 void nsp_texture_deinit()
 {
-       if(!has_colors)
-       {
-               (*(uint32_t*)0xC000001C) = ((*(uint32_t*)0xC000001C) & ~0b1110) | 0b0100; // Switch back to 4-bit mode
-               void *buf = SCREEN_BASE_ADDRESS;
-               SCREEN_BASE_ADDRESS = (void*) 0xA4000100;
-               free(buf);
-       }
+       // already de-init'ed by nspire-io
 }
 
 static mp_obj_t nsp_texture_make_new(const mp_obj_type_t *type_in, size_t n_args, size_t n_kw, const mp_obj_t *args)
@@ -108,8 +98,10 @@ static mp_obj_t nsp_texture_display(mp_obj_t self_in)
        
        if(self->width != 320 || self->height != 240 || self->has_transparency)
                nlr_raise(mp_obj_new_exception_msg(&mp_type_ValueError, "The texture must have the dimensions 320x240 without transparency!"));
-       else if(has_colors)
-               memcpy((uint16_t*)SCREEN_BASE_ADDRESS, self->bitmap, 320*240*2);
+       else
+               lcd_blit(self->bitmap, lcd_type());
+       /*
+       FIXME
        else
        {
                //Flip everything, as 0xFFFF is white on CX, but black on classic
@@ -118,6 +110,7 @@ static mp_obj_t nsp_texture_display(mp_obj_t self_in)
                while(--ptr32 >= (uint32_t*)self->bitmap)
                        *--ptr_inv32 = ~*ptr32;
        }
+       */
        
        return mp_const_none;
 }
```

With that applied, it still looks the same.

**Comment by Vogtinator** [comment]
Works fine here on HW-W in firebird, make sure that you run ```make clean``` so that no object files built with the old cflags remain.

```lcd_blit(self->bitmap, lcd_type());``` needs to be changed to ```lcd_blit(self->bitmap, SCR_320x240_565);``` though, the second argument is the format of the given buffer.

**Comment by The-Compiler** [comment]
Sorry for the late answer, but indeed, that helped!

**Comment by Vogtinator** [comment]
I applied the diff, raising an exception on non-cx for now.
